import type { QuranEdition } from "@/modules/quran/quran.schemas";

// Static, resolution-independent edition identity. Publish data (images/meta/
// previews + ornaments) is generated by the uploader into quran.publish.json and
// merged in by QuranService — so re-uploads never require code edits here.
export type EditionIdentity = Pick<
	QuranEdition,
	| "id"
	| "name"
	| "imageType"
	| "resolution"
	| "yearHijri"
	| "yearGregorian"
	| "linesPerPage"
	| "published"
>;

export const EDITION_IDENTITY: EditionIdentity[] = [
	{
		id: "v1",
		name: "Madinah Mushaf V1",
		imageType: "line",
		resolution: 1440,
		yearHijri: 1405,
		yearGregorian: 1984,
		linesPerPage: 15,
		published: true,
	},
	{
		id: "v2",
		name: "Madinah Mushaf V2",
		imageType: "line",
		resolution: 1440,
		yearHijri: 1420,
		yearGregorian: 1999,
		linesPerPage: 15,
		published: true,
	},
	{
		id: "v4",
		name: "Madinah Mushaf V4",
		imageType: "line",
		resolution: 1440,
		yearHijri: 1439,
		yearGregorian: 2017,
		linesPerPage: 15,
		published: true,
	},
];

// Every registered edition id — used to validate download events before they hit the DB.
export const EDITION_IDS: ReadonlySet<string> = new Set(
	EDITION_IDENTITY.map((identity) => identity.id),
);
