import { env } from "@/config/env";
import { audio } from "@/modules/quran/quran.audio";
import publishData from "@/modules/quran/quran.publish.json";
import type {
	QuranContent,
	QuranEdition,
	QuranManifest,
	QuranOrnaments,
} from "./quran.schemas";

const quranBase = `${env.CDN_URL}/quran`;

type EditionPublish = Pick<
	QuranEdition,
	"images" | "meta" | "previews" | "darkPreviews"
>;
const publish = publishData as {
	editions: Record<string, EditionPublish>;
	ornaments: QuranOrnaments;
	content?: QuranContent;
};

// Static, resolution-independent edition identity. Publish data (images/meta/
// previews + ornaments) is generated by the uploader into quran.publish.json and
// merged in below — so re-uploads never require code edits here.
type EditionIdentity = Pick<
	QuranEdition,
	| "id"
	| "name"
	| "imageType"
	| "resolution"
	| "yearHijri"
	| "yearGregorian"
	| "linesPerPage"
	| "published"
>;

const IDENTITY: EditionIdentity[] = [
	{
		id: "v1",
		name: "Madinah Mushaf V1",
		imageType: "line",
		resolution: 1440,
		yearHijri: 1405,
		yearGregorian: 1984,
		linesPerPage: 15,
		published: true,
	},
	{
		id: "v2",
		name: "Madinah Mushaf V2",
		imageType: "line",
		resolution: 1440,
		yearHijri: 1420,
		yearGregorian: 1999,
		linesPerPage: 15,
		published: true,
	},
	{
		id: "v4",
		name: "Madinah Mushaf V4",
		imageType: "line",
		resolution: 1440,
		yearHijri: 1439,
		yearGregorian: 2017,
		linesPerPage: 15,
		published: true,
	},
];

// Merge identity with generated publish data. Editions without publish data yet
// (uploader not run) are dropped, so the manifest only advertises live artifacts.
const editions = IDENTITY.flatMap((identity): QuranEdition[] => {
	const data = publish.editions[identity.id];
	return data ? [{ ...identity, ...data }] : [];
});

const MANIFEST: QuranManifest = {
	manifestSchema: 2,
	baseUrl: quranBase,
	editions,
	ornaments: publish.ornaments,
	// Omitted entirely until quran.publish.json carries a content block.
	...(publish.content && { content: publish.content }),
	audio,
};

// biome-ignore lint/complexity/noStaticOnlyClass: follows existing service pattern
export abstract class QuranService {
	static getManifest(): QuranManifest {
		return MANIFEST;
	}
}
